services:
  backend:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    command: ["./command.sh"]
    restart: always

  db:
    container_name: api-task-db
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-task
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
